#!/bin/bash
yum install -y httpd httpd-tools php gcc glibc glibc-common gd gd-devel make net-snmp
yum install -y httpd php php-cli gcc glibc glibc-common gd gd-devel net-snmp openssl openssl-devel wget unzip
useradd nagios
groupadd nagcmd
usermod -G nagcmd nagios
usermod -G nagcmd apache
mkdir /root/nagios
cd /root/nagios
wget https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.9.tar.gz
wget https://nagios-plugins.org/download/nagios-plugins-2.3.3.tar.gz
tar -xf nagios-4.4.9.tar.gz
 tar -xf nagios-plugins-2.3.3.tar.gz
 cd nagios-4.4.9/
 ./configure --with-command-group=nagcmd
 make all
 make install
 make install-init
 make install-commandmode
 make install-config
sudo rm -fr /usr/local/nagios/etc/objects/contacts.cfg
touch  /usr/local/nagios/etc/objects/contacts.cfg
cat  >> /usr/local/nagios/etc/objects/contacts.cfg  << EOF
# CONTACTS
#
###############################################################################

# Just one contact defined by default - the Nagios admin (that's you)
# This contact definition inherits a lot of default values from the
# 'generic-contact' template which is defined elsewhere.

define contact {

    contact_name            nagiosadmin             ; Short name of user
    use                     generic-contact         ; Inherit default values from generic-contact template (defined above)
    alias                      Nagios Admin         ; Full name of user
    email                   sudhirkumar.tcs@gmail.com ; <<***** CHANGE THIS TO YOUR EMAIL ADDRESS ******
}
EOF
cat  >> /usr/local/nagios/etc/objects/contacts.cfg  << EOF

############################################################

# We only have one contact in this simple configuration file, so there is
# no need to create more than one contact group.

define contactgroup {

    contactgroup_name       admins
    alias                   Nagios Administrators
    members                 nagiosadmin
}
EOF
make install-webconf
echo redhat | htpasswd -s -c -i /usr/local/nagios/etc/htpasswd.users nagiosadmin
systemctl start  httpd
cd  /root/nagios
cd  nagios-plugins-2.3.3
./configure --with-nagios-user=nagios --with-nagios-group=nagios
make
make install
systemctl enable nagios
systemctl enable httpd
systemctl restart nagios
systemctl start httpd
