#!/bin/bash
yum install -y httpd httpd-tools php gcc glibc glibc-common gd gd-devel make net-snmp
yum install -y httpd php php-cli gcc glibc glibc-common gd gd-devel net-snmp openssl openssl-devel wget unzip
useradd nagios
groupadd nagcmd
usermod -G nagcmd nagios
usermod -G nagcmd apache
mkdir /root/nagios
cd /root/nagios
wget https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.9.tar.gz
wget https://nagios-plugins.org/download/nagios-plugins-2.3.3.tar.gz
tar -xf nagios-4.4.9.tar.gz
 tar -xf nagios-plugins-2.3.3.tar.gz
 cd nagios-4.4.9/
 ./configure --with-command-group=nagcmd
 make all
 make install
 make install-init
 make install-commandmode
 make install-config
 cat >> /usr/local/nagios/etc/objects/contacts.cfg << EOF
define contact {
contact_name        nagiosadmin
use                 generic-contact
alias               Nagios Admin
email               admin@tecmint.com
}
EOF
make install-webconf
systemctl start  httpd
cd /root/nagios
cd nagios-plugins-2.3.3
./configure --with-nagios-user=nagios --with-nagios-group=nagios
make
make install
systemctl enable nagios
systemctl enable httpd
systemctl restart nagios
systemctl start httpd
